name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '39 9 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v5.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: >
            This issue is stale because it has been open 30 days with no activity.
            Remove the stale label or comment to keep it open. Otherwise it will be closed in 5 days.
          stale-pr-message: >
            This PR is stale because it has been open 30 days with no activity.
            Remove the stale label or comment to keep it open. Otherwise it will be closed in 10 days.
          close-issue-message: >
            This issue was closed because it has been stale for 5 additional days with no activity.
          stale-issue-label: 'no-issue-activity'
          stale-pr-label: 'no-pr-activity'
          days-before-stale: 30
          days-before-pr-stale: 30
          days-before-close: 5
          days-before-pr-close: 10
          exempt-assignees: 'eds2002'
